# Additional loggers to configure (the root logger is always configured)
loggers=dev.snowdrop.rewrite.logging

logger.level=INFO
logger.handlers=COLOR-HANDLER

logger.dev.snowdrop.rewrite.logging.level=WARN
logger.dev.snowdrop.rewrite.logging.useParentHandlers=true

handler.COLOR-HANDLER=dev.snowdrop.rewrite.logging.ColorHandler
handler.COLOR-HANDLER.level=DEBUG
handler.COLOR-HANDLER.properties=autoFlush
handler.COLOR-HANDLER.autoFlush=true
handler.COLOR-HANDLER.formatter=PATTERN

formatter.PATTERN=org.jboss.logmanager.formatters.ColorPatternFormatter
formatter.PATTERN.properties=pattern
formatter.PATTERN.pattern=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n