# Quarkus application configuration
quarkus.application.name=rewrite-client
quarkus.application.version=0.3.1-SNAPSHOT

quarkus.class-loading.parent-first-artifacts=org.jboss.logmanager:jboss-logmanager,org.apache.maven.resolver:maven-resolver-spi,org.apache.maven.resolver:maven-resolver-impl,org.apache.maven.resolver:maven-resolver-named-locks

# Logging configuration for DEV
%dev.quarkus.log.level=INFO
%dev.quarkus.log.console.enabled=true

# Logging & banner configuration for PROD, Client mode when running picocli
%prod.quarkus.banner.enabled=false
%prod.quarkus.log.console.enabled=false
%prod.cli.log.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
%prod.cli.log.level=INFO
%prod.cli.log.category."dev.snowdrop.rewrite".level=INFO
#%prod.cli.log.category."dev.snowdrop.rewrite.cli.logging".level=DEBUG

# Temporary workaround used to allow to log TRACE messages in PROD when using -vv
# From James Perkins: AFAIK the only way around the min-level issue is to set it in the application.properties or
# implement a org.jboss.logmanager.LogContextInitializer and set it on the LogContext.
# The constructor of the LoggerNode is where you'll see how the effectiveMinLevel is set https://github.com/jboss-logging/jboss-logmanager/blob/e59884bcd3e1f40a5d3c3dffe3688ba6a60442b1/src/main/java/org/jboss/logmanager/LoggerNode.java#L138-L155
%prod.quarkus.log.min-level=TRACE

# rewrite CLI Configuration
# Default values that can be overridden by environment variables
rewrite.config-location=${REWRITE_CONFIG_LOCATION:rewrite.yml}
rewrite.size-threshold-mb=${REWRITE_SIZE_THRESHOLD_MB:10}
rewrite.export-datatables=${REWRITE_EXPORT_DATATABLES:false}
rewrite.fail-on-invalid-active-recipes=${REWRITE_FAIL_ON_INVALID_ACTIVE_RECIPES:false}
rewrite.dry-run=${REWRITE_DRY-RUN:true}

# Plain text masks used by the OmniParser to fetch/parse the text files
#rewrite.plain-text-masks=**/*.adoc,**/*.bash,...

# Default exclusions
rewrite.exclusions=**/target/**,**/.git/**,**/.idea/**,**/build/**,**/node_modules/**

# Native image configuration (if building with GraalVM)
quarkus.native.additional-build-args=--allow-incomplete-classpath,--report-unsupported-elements-at-runtime